### ISSUE TITLE
Cannot resolve "Conflict rule(s) detected in ./tslint.json" = quotemark

### ISSUE THREAD

**Issue by schtauffen** [alexjoverm/tslint-config-prettier#139]
In my _.prettierrc_
```
{
  "singleQuote": true
}
```

_tslint.json_
```
{
  "defaultSeverity": "error",
  "extends": ["tslint:recommended", "tslint-react", "tslint-config-prettier"],
  "jsRules": {},
  "rules": {
    "quotemark": [true, "single"],
    "trailing-comma": [false]
  },
  "rulesDirectory": []
}
```

I believe I have tslint and prettier configured to use single-quotes. VSCode respects the tslint rule for syntax highlighting, and running prettier on the files uses single quotes as expected. However, running the command `tslint-config-prettier-check ./tlint.json` displays conflict with _quotemark_.

**Comment by ikatyang** [comment]
The goal of this project is to disable all prettier-related rules and let prettier take care of it, that's why `tslint-config-prettier-check` will throw in this case.

And also, [`singleQuote` option in prettier](https://prettier.io/docs/en/rationale.html#strings) is not 100% compatible with [`quotemark` rule in tslint](https://palantir.github.io/tslint/rules/quotemark/).

If you'd like to see the prettier error highlighting with tslint, [`tslint-plugin-prettier`](https://github.com/ikatyang/tslint-plugin-prettier) is your friend.

**Comment by alexjoverm** [comment]
Seems like we can close this issue. @schtauffen feel free to open otherwise
