### ISSUE TITLE
Prettier over writes tslint rule

### ISSUE THREAD

**Issue by arrayoutofbounds** [alexjoverm/tslint-config-prettier#172]
The rule `object-literal-key-quotes` requires the quotes to be there for a key in an object. However, prettier removes them because I believe keys without special character do not need quotes. So, when I run lint locally, it runs perfectly fine. However, I run prettier before I push it up and that ends up over writing and removing the quotes. So, when I run the pipelines in the bitbucket repo, I get lint failures. Would love a solution around this!
Thank you!

**Comment by ikatyang** [comment]
Hi, that's why `tslint-config-prettier` exists, we disable all the rules that conflict with Prettier, and we do disable the [`object-literal-key-quotes`](https://github.com/alexjoverm/tslint-config-prettier/tree/master/src/tslint/object-literal-key-quotes) rule, see [Get Started](https://github.com/alexjoverm/tslint-config-prettier#get-started) for how to use it.
